Improve the ReadMe to provide more details and useful links
idrsolutions/buildvu-docker pull request #8
Opened 2021-08-18 11:30 UTC by KieranFrance

2021-08-18 13:21 UTC, daniel-warren requested changes
Changes look promising, I made some suggestions on how I think it could be improved.

2021-08-18 13:21 UTC, daniel-warren commented on README.md
> +BuildVu is a PDF to HTML or SVG conversion tool to allow you to display documents natively in the web browser on any smartphone, tablet, PC or Mac. This docker image can be used to containerise Build
```suggestion
BuildVu is a PDF to HTML or SVG conversion tool to allow you to display documents natively in the web browser on any smartphone, tablet, PC or Mac. This docker image can be used to containerise BuildVu making it accessible via a REST API which is perfect for cloud deployments.
```

2021-08-18 13:21 UTC, daniel-warren commented on README.md
> +To build the image from the source use the following steps.
```suggestion
To build the image from source, use the following steps.
```

2021-08-18 13:21 UTC, daniel-warren commented on README.md
> +In order to use the BuildVu Docker image you will need a license to access the BuildVu war file. If you have not got a license yet, you can find a [free trial or contact us here](https://www.idrsolut
```suggestion
In order to use the BuildVu Docker image you will need a license to access the BuildVu war file. If you have not got a license yet, you can find our [free trial or contact us here](https://www.idrsolutions.com/buildvu/pricing).
```

2021-08-18 13:21 UTC, daniel-warren commented on README.md
> +Once you have access you can get and run the docker image with the following commands.
```suggestion
Once you have access, you can get and run the docker image with the following commands.
```

2021-08-26 10:06 UTC, leonatherton commented
What do you think about swapping the _Getting Started_ and _Building the Image_ sections? My thinking is that most people just want to run the image, whereas building it yourself is for more advanced use-cases and is not part of the standard workflow.

Same applies to PRs for the other products.

2021-08-26 13:14 UTC, KieranFrance commented
All suggested changes have been implemented and I reordered the sections as I agree with Leons  thoughts on the order (also implemented in the other PRs)

Please update the review if you are happy with the changes

2021-08-27 11:48 UTC, daniel-warren approved these changes

2021-08-31 15:46 UTC, leonatherton requested changes

2021-08-31 15:46 UTC, leonatherton commented on README.md
> +Once you have access, you can get and run the docker image with the following commands.
```suggestion
Once you have the BuildVu war file, you can pull and run the docker image with the following commands:
```

2021-08-31 15:46 UTC, leonatherton commented on README.md
> +In order to use the BuildVu Docker image you will need a license to access the BuildVu war file. If you have not got a license yet, you can find our [free trial or contact us here](https://www.idrsol
```suggestion
In order to use the BuildVu Docker image you will need a license to access the BuildVu war file. If you have not got a license yet, you can [sign up for a free trial](https://www.idrsolutions.com/buildvu/trial-download).
```

2021-08-31 15:46 UTC, leonatherton commented on README.md
> +[IDRSolutions BuildVu Docker Support Page](https://support.idrsolutions.com/buildvu/tutorials/cloud/docker).
```suggestion
[BuildVu Docker Documentation](https://support.idrsolutions.com/buildvu/tutorials/cloud/docker).
[Contact IDRsolutions](https://www.idrsolutions.com/contact-us)
```

2021-08-31 15:46 UTC, leonatherton commented on README.md
> +[IDRSolutions BuildVu Cloud Support Page](https://support.idrsolutions.com/buildvu/tutorials/cloud/).
```suggestion
[BuildVu Cloud Documentation](https://support.idrsolutions.com/buildvu/tutorials/cloud/).  
```

2021-09-01 12:45 UTC, KieranFrance commented
The suggested changes have now been implemented

2021-09-01 12:45 UTC, KieranFrance commented
The suggested changes have now been implemented

2021-09-01 15:40 UTC, leonatherton approved these changes

2021-09-09 08:15 UTC, merged